# -*- coding: utf-8 -*-
"""cleaning_data_film.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NVjVryIrHAH1_WSTd_RTwbKEfNK8JEOV
"""

import pandas as pd

df = pd.read_excel("/content/Project_intern.xlsx")

print(type(df))
print(df.head())

df.head()

"""##Hapus duplikat"""

df.info()

df.drop_duplicates(subset ="judul", keep = 'first', inplace = True)

df.info()

"""##misssing value"""

df.isnull().sum()

import pandas as pd

# baca langsung Excel ke DataFrame
df = pd.read_excel("/content/Project_intern.xlsx")

print(type(df))   # harusnya <class 'pandas.core.frame.DataFrame'>
print(df.head())  # lihat 5 baris pertama

## mengetahui informasi data
df.info()

##menghapus duplikat
df.drop_duplicates(subset ="judul", keep = 'first', inplace = True)

##mengetahui info data setelah menghapus duplikat
df.info()

##mencari missing values
df.isna().sum()

# Hapus semua baris yang punya minimal 1 nilai NaN
df_clean = df.dropna(how="any")

print("Jumlah baris sebelum:", df.shape[0])
print("Jumlah baris sesudah :", df_clean.shape[0])

##informasi data setelah handling missing values
df_clean.info()

#informasi data
df_clean.describe()
df_clean.shape

#memastikan kembali tidak ada missing values
df_clean.isna().sum()

# Simpan dataframe ke file CSV
df_clean.to_csv("data_film_bersih.csv", index=False)

